version: '3'

services:
    webserver_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_WEB_SERVER_1
        build: ./httpd/1
        expose:
            - ${APACHE_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APACHE_1_IP}
    webserver_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_WEB_SERVER_2
        build: ./httpd/2
        expose:
            - ${APACHE_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APACHE_2_IP}
    haloadbalancer:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - APACHE_1_IP=${APACHE_1_IP}
            - APACHE_2_IP=${APACHE_2_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}